### ISSUE TITLE
bytesToHex is missing?

### ISSUE THREAD

**Issue by GeorgioWan** [dave-irvine/packbits#1]
Hi,
I'm using the **packbits** module currently and found that **bytesToHex** didn't define in **encode.js**, is there really missing or just misunderstanding?

**Comment by dave-irvine** [comment]
Whoops! Fixed in https://github.com/dave-irvine/packbits/commit/5224260f38472aaaf935dcfc581f59b84d99e6bf, published in 1.0.1

Let me know if it works.

**Comment by GeorgioWan** [comment]
It works, thanks!
